ViewComponentsExample/Models/Person.cs
namespace ViewComponentsExample.Models
{
    public class Person
    {
        public string? PersonName { get; set; }
        public string? JobTitle { get; set; }
    }
}

ViewComponentsExample/Models/PersonGrid.cs
namespace ViewComponentsExample.Models
{
    public class PersonGrid
    {
        public string GridTitle { get; set; } = string.Empty;
        public List<Person> Persons { get; set; } = new List<Person>();

    }
}

ViewComponentsExample/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ViewComponentsExample.Models;

namespace ViewComponentsExample.Controllers
{
    public class HomeController : Controller
    {
        [Route("/")]
        public IActionResult Index()
        {
            return View();
        }
        [Route("about")]
        public IActionResult About()
        {
            return View();
        }
        [Route("friend-list")]
        public IActionResult LoadFriendList()
        {
            PersonGrid personGrid = new PersonGrid()
            {
                GridTitle = "Employess",
                Persons = new List<Person>(){
                 new Person (){PersonName = "Yuvaraj" , JobTitle = "System Engineer"},
                 new Person ()  {PersonName = "Sudhir" , JobTitle = "Consultant"},
                  new Person () {PersonName = "Sunil" , JobTitle = "Manager"}
                 }
            };

            return ViewComponent("Grid",new { grid = personGrid});
        }
    }
}

ViewComponentsExample/ViewComponents/GridViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ViewComponentsExample.Models;

namespace ViewComponentsExample.ViewComponents
{
    public class GridViewComponent : ViewComponent
    {
       public async Task <IViewComponentResult> InvokeAsync(PersonGrid grid)
        {
            PersonGrid model = new PersonGrid()
            {
                GridTitle = "Persons List",
                Persons = new List<Person>
                {
                    new Person() { PersonName = "John", JobTitle = "Engineer" },
                    new Person() { PersonName = "Billu", JobTitle = "Technician" },
                    new Person() { PersonName = "Sameer", JobTitle = "Donker" }
                }
            
            };
            ViewData["Grid"] = model;
            //strongly typed view components
            return View("Sample",grid); //invoke a partial Views/ Shared/Components/Grid/Default.cshtml

        }
    }
}

ViewComponentsExample/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h1>
    About
</h1>

<button class="button button-blue-back" id="load-friends-button">Load Friends</button>

<div id="list"> 

</div>
<script src="~/friends.js"></script>

ViewComponentsExample/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}
<h1>
    Home
</h1>
@{
    PersonGrid personGrid = new PersonGrid()
    {
        GridTitle = "Persons",
        Persons = new  List<Person>(){
            new Person (){PersonName = "PulliSeth" , JobTitle = "Actress"},
            new Person ()  {PersonName = "Vinayrao" , JobTitle = "Manager"},
            new Person () {PersonName = "Payaljii" , JobTitle = "Teacher"}
        }
    };
}
@await Component.InvokeAsync("Grid" , new {
     grid = personGrid

})

@{
    PersonGrid personGrid2 = new PersonGrid()
            {
                GridTitle = "Frinds",
                Persons = new List<Person>(){
            new Person (){PersonName = "Vikrant" , JobTitle = "Engineer"},
            new Person ()  {PersonName = "Aditya" , JobTitle = "Manager"},
            new Person () {PersonName = "Rohit" , JobTitle = "Govt Employee"}
        }
            };
}
@await Component.InvokeAsync("Grid" , new {
     grid = personGrid2

})

ViewComponentsExample/Views/Shared/Components/Grid/Sample.cshtml
@model PersonGrid
<div class="box">
    @*<h3>@ViewBag.Grid.GridTitle</h3>*@
    <h3>@Model.GridTitle</h3>
    <table class="table w-100">
        <thead>
            <tr>
                <th>Sr. No</th>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Person person in Model.Persons)
            {
               <tr>
                    <td>@person.PersonName</td>
                    <td>@person.JobTitle</td>
                </tr>
            }
        </tbody>
    </table>
</div>

ViewComponentsExample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Stylesheet.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="navbar">
            <div class="navbar-brand">
                View Component Demo App
            </div>
            <ul>
                <li><a href="~/">Home</a></li>
                <li><a href="~/about">About</a></li>

                
            </ul>
        </div>
        <div class="page-content">
            @RenderBody()
        </div>
       
    </div>
</body>
</html>